version: "2"

networks:
  default:
    attachable: true
    name: "neko-rooms-net"

services:
  coder:
    image: coder:latest
    volumes:
      - /root/github/gbrian/codx-neko-rooms:/home/coder/neko-rooms
    ports:
      - 9080:9080
