version: "2"

networks:
  default:
    attachable: true
    name: "${NEKO_ROOMS_TRAEFIK_NETWORK}"

services:
  registry:
    image: registry:latest
    environment:
    #  REGISTRY_AUTH: htpasswd
    #  REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    #  REGISTRY_AUTH_HTPASSWD_PATH: /auth/usersfile
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /registry
    restart: unless-stopped
    user: root
    volumes:
      - "/root/github/gbrian/codx-neko-rooms/usersfile:/auth/usersfile"
      - "/mnt/HC_Volume_24235669/registry:/registry"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.registry.rule=Host(`${NEKO_ROOMS_REGISTRY_DOMAIN}`)"
      - "traefik.http.routers.registry.entrypoints=${NEKO_ROOMS_TRAEFIK_ENTRYPOINT}"
      - "traefik.http.routers.registry.service=registry"
      - "traefik.http.services.registry.loadbalancer.server.port=5000"

  traefik:
    links:
      - neko-rooms
    container_name: "traefik"
    image: "traefik:latest"
    restart: unless-stopped
    environment:
      - "API_BASE_URL"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--accesslog=true"
      - "--providers.file.directory=/traefik-conf"
      - "--providers.file.watch=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=neko-rooms-net"
      - "--providers.http=true"
      - "--providers.http.endpoint=${API_PROXY_CONF_ENDPOINT}"
      - "--providers.http.pollInterval=15s"
      - "--entryPoints.web.forwardedHeaders.insecure"
      - "--entrypoints.web.address=:8000"
    ports:
      - "8000:8000"
      - "8800:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/root/github/gbrian/codx-neko-rooms/usersfile:/usersfile"
      - "/root/github/gbrian/codx-neko-rooms/traefik-conf.yaml:/traefik-conf/base-conf.yaml"

