version: "2"

services:
  neko-rooms:
    container_name: "neko-rooms"
    image: "academy-hub.meetnav.com/codx/neko-rooms:latest"
    build:
      context: neko-rooms
    restart: "unless-stopped"
    environment:
      - "TZ"
      - "NEKO_ROOMS_EPR"
      - "NEKO_ROOMS_NAT1TO1"
      - "NEKO_ROOMS_TRAEFIK_DOMAIN=${NEKO_ROOMS_NAT1TO1}"
      - "NEKO_ROOMS_INSTANCE_URL=http://${NEKO_ROOMS_NAT1TO1}:8000/"
      - "NEKO_ROOMS_TRAEFIK_ENTRYPOINT"
      - "NEKO_ROOMS_TRAEFIK_NETWORK"
      - "NEKO_ROOMS_LOGS"
      - "NEKO_ROOMS_NEKO_IMAGES"
      - "NEKO_ROOMS_NEKO_PRIVILEGED_IMAGES"
      - "NEKO_ROOMS_DEBUG"
      - "NEKO_ROOMS_PATH_PREFIX=/neko-rooms/"
      - "NEKO_ROOMS_STORAGE_ENABLED=true"
      - "NEKO_ROOMS_MOUNTS_WHITELIST"
      - "NEKO_ROOMS_STORAGE_INTERNAL"
      - "NEKO_ROOMS_STORAGE_EXTERNAL"
      - "VUE_APP_BASE_URL=/neko-rooms/"
      - "NEKO_ROOMS_RCLONE_TOKEN"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${DATA_PATH}:/shared"

  # koneko-dev:
  #   image: node:18
  #   container_name: koneko-dev
  #   working_dir: /src
  #   command: bash -c "yarn && yarn build && yarn dev"
  #   volumes:
  #     - "$CODX_PATH/koneko:/src"
  #   restart: unless-stopped
  #   env_file:
  #     - .env
  #   environment:
  #     - KONEKO_API_TOKEN
  #     - KONEKO_PROVIDER
  #     - KONEKO_HETZNER_API_TOKEN
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.koneko-dev.rule=Host(`koneko-dev.meetnav.com`)"
  #     - "traefik.http.routers.koneko-dev.priority=1000"
  #     - "traefik.http.routers.koneko-dev.entrypoints=${NEKO_ROOMS_TRAEFIK_ENTRYPOINT}"
  #     - "traefik.http.routers.koneko-dev.service=koneko-dev"
  #     - "traefik.http.services.koneko-dev.loadbalancer.server.port=3000"

  traefik:
    links:
      - neko-rooms
    container_name: "traefik"
    image: "traefik:latest"
    restart: unless-stopped
    environment:
      - "API_BASE_URL"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--accesslog=true"
      - "--providers.file.directory=/traefik-conf"
      - "--providers.file.watch=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=neko-rooms-net"
      - "--providers.http=true"
      - "--providers.http.endpoint=${API_PROXY_CONF_ENDPOINT}"
      - "--providers.http.pollInterval=15s"
      - "--entryPoints.web.forwardedHeaders.insecure"
      - "--entrypoints.web.address=:8000"
    ports:
      - "8000:8000"
      - "8800:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./usersfile:/usersfile"
      - "./traefik-conf.yaml:/traefik-conf/base-conf.yaml"


networks:
  default:
    external: true
    name: $NEKO_ROOMS_TRAEFIK_NETWORK