version: "2"

networks:
  default:
    attachable: true
    name: "${NEKO_ROOMS_TRAEFIK_NETWORK}"

services:
  neko-rooms:
    container_name: "neko-rooms"
    image: "academy-hub.meetnav.com/codx/neko-rooms:latest"
    build:
      context: neko-rooms
    restart: "unless-stopped"
    environment:
      - "TZ"
      - "NEKO_ROOMS_EPR"
      - "NEKO_ROOMS_NAT1TO1"
      - "NEKO_ROOMS_TRAEFIK_DOMAIN=${NEKO_ROOMS_NAT1TO1}"
      - "NEKO_ROOMS_INSTANCE_URL=http://${NEKO_ROOMS_NAT1TO1}:8000/"
      - "NEKO_ROOMS_TRAEFIK_ENTRYPOINT"
      - "NEKO_ROOMS_TRAEFIK_NETWORK"
      - "NEKO_ROOMS_LOGS"
      - "NEKO_ROOMS_NEKO_IMAGES"
      - "NEKO_ROOMS_NEKO_PRIVILEGED_IMAGES"
      - "NEKO_ROOMS_DEBUG"
      - "NEKO_ROOMS_PATH_PREFIX=/neko-rooms/"
      - "VUE_APP_BASE_URL=/neko-rooms/"
      - "NEKO_ROOMS_RCLONE_TOKEN"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  traefik:
    links:
      - neko-rooms
    container_name: "traefik"
    image: "traefik:latest"
    restart: unless-stopped
    environment:
      - "API_BASE_URL"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--accesslog=true"
      - "--providers.file.directory=/traefik-conf"
      - "--providers.file.watch=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=neko-rooms-net"
      - "--providers.http=true"
      - "--providers.http.endpoint=${API_PROXY_CONF_ENDPOINT}"
      - "--providers.http.pollInterval=15s"
      - "--entryPoints.web.forwardedHeaders.insecure"
      - "--entrypoints.web.address=:8000"
    ports:
      - "8000:8000"
      - "8800:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/root/github/gbrian/codx-neko-rooms/usersfile:/usersfile"
      - "/root/github/gbrian/codx-neko-rooms/traefik-conf.yaml:/traefik-conf/base-conf.yaml"

