version: "3.8"
services:
  codx:
    image: academy-hub.meetnav.com/codx/codx-room:latest
    container_name: codx
    restart: unless-stopped
    shm_size: 2gb
    network_mode: "host"
    environment:
      - "NEKO_BIND=$NEKO_BIND"
      - "NEKO_EPR=${NEKO_EPR:-52000-52001}"
      - "NEKO_ICELITE=$NEKO_ICELITE"
      - "NEKO_NAT1TO1=$NEKO_NAT1TO1"
      - "NEKO_PASSWORD=$NEKO_PASSWORD"
      - "NEKO_PASSWORD_ADMIN=$NEKO_PASSWORD_ADMIN"
      - "NEKO_SCREEN=$NEKO_SCREEN"
      - "NEKO_MAX_FPS=$NEKO_MAX_FPS"
      - "NEKO_VP8=$NEKO_VP8"
      - "NEKO_VIDEO_BITRATE=$NEKO_VIDEO_BITRATE"
      - "NEKO_OPUS=$NEKO_OPUS"
      - "NEKO_AUDIO_BITRATE=$NEKO_AUDIO_BITRATE"
      - "PASSWORD="
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/shared:/shared"
      - "/shared/codx:/home/codx/.local/share/code-server"
